/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.csee.se.sugarbag.plugin;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
